### ISSUE TITLE
Excellent Github Actions integration

### ISSUE THREAD

**Issue by certik** [prefix-dev/shell#178]
So that you can use `interpreter: shell` and write your scripts cross platform with ease. We could add something like:
```yaml
- uses: prefix-dev/shell
  with:
    tools: [grep, sed, awk, curl]
```
And then pixi would go and fetch them if they are not yet on the disk, and cache them.
